version: "3.0"
services:
  app:
    volumes:
      - ./app:/app
    build: ./config
    # command: python src.py
    tty: true
    network_mode: host
    deploy:
      resources:
          reservations:
              devices:
                  - capabilities: [gpu]
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    extra_hosts:
      - "host.docker.internal:host-gateway" # ホスト側のポートに接続